language: EN
# strict: true
# strictness_threshold: high
strict: false
# output:
#   file_path: results.csv
#   format: CSV
sast:
  include:
    - .
  exclude:
    - .github
    - node_modules
    - vendor
